services:
  db:
    image: postgres:15.3-alpine
    container_name: widget-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: widget-server-db

  app:
    build: .
    container_name: widget-server
    ports:
      - 3001:3333
    environment:
      - CLOUDFLARE_ACCESS_KEY_ID=#
      - CLOUDFLARE_SECRET_ACCESS_KEY=#
      - CLOUDFLARE_BUCKET=#
      - CLOUDFLARE_ACCOUNT_ID=#
      - CLOUDFLARE_PUBLIC_URL=http://localhost