name: Deploy widget-server image to AWS ECR
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Generate tag
        id: generate-tag
        run: |
          SHA_IMAGE_TAG=$(echo $GITHUB_SHA | head -c7)
          echo "sha_image_tag=$SHA_IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Build and push the image to AWS ECR with docker/build-push-action@v6
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{steps.login-ecr.outputs.registry}}/${{ vars.ECR_REPOSITORY }}:${{ steps.generate-tag.outputs.sha }}

      # - name: Build and push image to Amazon ECR
      #   id: build-push-image
      #   env:
      #     SHA_IMAGE_TAG: ${{ steps.generate-tag.outputs.sha_image_tag }}
      #     ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
      #     ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
      #   run: |
      #     PUSH_IMAGE_URL="${ECR_REGISTRY}/${ECR_REPOSITORY}:${SHA_IMAGE_TAG}"
      #     echo "Building image with tag: $PUSH_IMAGE_URL"
      #     docker build -t "$PUSH_IMAGE_URL" .
      #     docker push "$PUSH_IMAGE_URL"